Object.assign(window.PLX_T,{
"Wissen gehört nicht in die Schublade.":{fr:"Le savoir est fait pour circuler.",en:"Knowledge should be shared."},
"Mehr Daten. Weniger Ego.":{fr:"Plus de données. Moins d’ego.",en:"More data. Less ego."},
"Leistung entsteht durch Beobachtung, Anpassung und saubere Wiederholbarkeit.":{fr:"La performance naît de l’observation, de l’adaptation et d’une exécution reproductible.",en:"Performance comes from observation, adaptation and consistent repeatability."},
"Karriere":{fr:"Carrière",en:"Career"},
"Talent braucht Kontext.":{fr:"Le talent a besoin de contexte.",en:"Talent needs context."},
"Umfeld, Kontakte und ein klares Ziel können mehr verändern als Reichweite allein.":{fr:"L’environnement, les contacts et un objectif clair peuvent compter davantage que la visibilité seule.",en:"Environment, connections and a clear goal can matter more than reach alone."},
"Mit PowerLux arbeiten":{fr:"Travailler avec PowerLux",en:"Work with PowerLux"},
"Kooperationen für Events, Clubs, Brands und neue Projekte.":{fr:"Collaborations pour événements, clubs, marques et nouveaux projets.",en:"Collaborations for events, clubs, brands and new projects."},
"Workshop, Challenge, Aktivierung oder gemeinsames Format.":{fr:"Atelier, challenge, activation ou format commun.",en:"Workshop, challenge, activation or joint format."},
"Talente, Wissen, Projekte und langfristige Zusammenarbeit.":{fr:"Talents, expertise, projets et collaboration à long terme.",en:"Talent, knowledge, projects and long-term collaboration."},
"Benefits, Sponsoring und Kampagnen mit klarem Community-Wert.":{fr:"Avantages, sponsoring et campagnes avec une valeur claire pour la communauté.",en:"Benefits, sponsorships and campaigns with clear community value."},
"Idee / Mitarbeit":{fr:"Idée / Contribution",en:"Idea / Contribution"},
"Content, Entwicklung, Design oder ein neuer Ansatz.":{fr:"Contenu, développement, design ou nouvelle approche.",en:"Content, development, design or a new approach."},
"Wähle deine Rolle. PowerLux verbindet Athleten, Coaches, Clubs, Unternehmen und öffentliche Akteure mit konkreten nächsten Schritten.":{fr:"Choisissez votre rôle. PowerLux relie athlètes, coaches, clubs, entreprises et acteurs publics à des prochaines étapes concrètes.",en:"Choose your role. PowerLux connects athletes, coaches, clubs, companies and public stakeholders with concrete next steps."},
"Partnerschaften, Projekte und Förderanträge werden vorbereitet; formale ASBL-Schritte folgen nach der Eintragung.":{fr:"Les partenariats, projets et demandes de financement sont en préparation ; les étapes formelles de l’ASBL suivront après l’enregistrement.",en:"Partnerships, projects and funding applications are being prepared; formal ASBL steps follow after registration."},
"Unterstützung & Entwicklung":{fr:"Soutien & développement",en:"Support & development"},
"Talentprofil, Coaching-Zugang, Club-Verbindung oder ein konkretes sportliches Anliegen.":{fr:"Profil talent, accès au coaching, mise en relation avec un club ou besoin sportif concret.",en:"Talent profile, coaching access, club connection or a specific sporting need."},
"START REQUEST →":{fr:"DÉMARRER →",en:"START REQUEST →"},
"Wissen einbringen":{fr:"Partager son expertise",en:"Contribute expertise"},
"Coaching, Seminare, Technik, Sicherheit oder fachliche Zusammenarbeit.":{fr:"Coaching, séminaires, technique, sécurité ou collaboration spécialisée.",en:"Coaching, seminars, technique, safety or specialist collaboration."},
"CONNECT →":{fr:"SE CONNECTER →",en:"CONNECT →"},
"Netzwerk verbinden":{fr:"Connecter le réseau",en:"Connect the network"},
"Events, Resultate, Athleten, Rankings und gemeinsame Sportprojekte.":{fr:"Événements, résultats, athlètes, classements et projets sportifs communs.",en:"Events, results, athletes, rankings and joint sports projects."},
"CONNECT CLUB →":{fr:"CONNECTER LE CLUB →",en:"CONNECT CLUB →"},
"Partner werden":{fr:"Devenir partenaire",en:"Become a partner"},
"Projekt-, Event-, Equipment-, Affiliate- oder strategische Partnerschaft mit nachvollziehbarem Community-Wert.":{fr:"Partenariat de projet, d’événement, d’équipement, d’affiliation ou stratégique avec une valeur claire pour la communauté.",en:"Project, event, equipment, affiliate or strategic partnership with clear community value."},
"PARTNER ROUTE →":{fr:"PARCOURS PARTENAIRE →",en:"PARTNER ROUTE →"},
"Projekt entwickeln":{fr:"Développer un projet",en:"Build a project"},
"Jugend, Einstieg in Kraftsport, Workshops oder lokale Aktivierung gemeinsam strukturieren.":{fr:"Structurer ensemble des projets jeunesse, d’initiation aux sports de force, des ateliers ou des activations locales.",en:"Structure youth projects, introductions to strength sports, workshops or local activations together."},
"BUILD PROJECT →":{fr:"DÉVELOPPER LE PROJET →",en:"BUILD PROJECT →"},
"Mission stärken":{fr:"Renforcer la mission",en:"Strengthen the mission"}
});

