window.PLX_T={
"Aktuelle Sportmeldung wird geladen.":{fr:"La dernière actualité sportive est en cours de chargement.",en:"Loading the latest sports update."},
"Weiter zum Hub":{fr:"Entrer dans le Hub",en:"Enter the Hub"},
"♫ Musik im Hub: an · 14%":{fr:"♫ Musique du Hub : active · 14 %",en:"♫ Hub music: on · 14%"},
"Story lesen":{fr:"Lire l’actualité",en:"Read story"},
"Athleten · Clubs · Events":{fr:"Athlètes · Clubs · Événements",en:"Athletes · Clubs · Events"},
"Luxemburg":{fr:"Luxembourg",en:"Luxembourg"},
"Luxemburgs Übersicht für News, Events, Resultate, Rankings, Clubs, Benefits und Talente im Kraft- und Nischensport.":{fr:"Le hub luxembourgeois pour l’actualité, les événements, les résultats, les classements, les clubs, les avantages et les talents des sports de force et de niche.",en:"Luxembourg’s hub for news, events, results, rankings, clubs, benefits and talents across strength and niche sports."},
"Aktuelles ansehen":{fr:"Voir les actualités",en:"View latest"},
"Finde Athleten, Clubs, Events und Resultate aus Luxemburgs Kraft- und Nischensport. Quellen führen direkt zum Original.":{fr:"Découvrez athlètes, clubs, événements et résultats des sports de force et de niche au Luxembourg. Chaque source renvoie vers l’original.",en:"Discover athletes, clubs, events and results from Luxembourg’s strength and niche sports. Sources link directly to the original."},
"Originalquellen":{fr:"Sources originales",en:"Original sources"},
"Talent melden":{fr:"Proposer un talent",en:"Submit talent"},
"Aktuelle Sportmeldungen mit Originalquelle.":{fr:"Actualités sportives récentes avec source originale.",en:"Current sports news with original sources."},
"Alle":{fr:"Tous",en:"All"},
"News-Feed wird geladen…":{fr:"Chargement du fil d’actualités…",en:"Loading news feed…"},
"Termine und Veranstaltungen mit Originalquelle.":{fr:"Dates et événements avec source originale.",en:"Dates and events with original sources."},
"Offizielle Quelle ↗":{fr:"Source officielle ↗",en:"Official source ↗"},
"Leistungen, Rekorde und Ergebnisse mit Originalquelle.":{fr:"Performances, records et résultats avec source originale.",en:"Performances, records and results with original sources."},
"Luxemburgs Ranking-Hub für Kraft- und Performance-Sport. Wähle Sportart, Division und Gewichtsklasse. Eigene Ranglisten werden als":{fr:"Le hub de classement luxembourgeois pour les sports de force et de performance. Choisissez le sport, la division et la catégorie de poids. Les classements PowerLux sont identifiés comme",en:"Luxembourg’s ranking hub for strength and performance sports. Choose sport, division and weight class. PowerLux-managed rankings are identified as"},
"geführt; offizielle Verbandsdaten erscheinen separat und mit Originalquelle.":{fr:"; les données officielles des fédérations sont affichées séparément avec leur source originale.",en:"; official federation data is displayed separately with the original source."},
"Clubs und Trainingsorte in Luxemburg. Kontakt- und Trainingsdaten direkt beim Club oder Verband prüfen.":{fr:"Clubs et lieux d’entraînement au Luxembourg. Vérifiez les coordonnées et horaires directement auprès du club ou de la fédération.",en:"Clubs and training locations in Luxembourg. Verify contact and training details directly with the club or federation."},
"Aktuelle Angebote und Rabatte mit direktem Anbieterlink. Rabattcodes erscheinen nur, wenn sie in der Quelle stehen.":{fr:"Offres et réductions actuelles avec lien direct vers le fournisseur. Les codes ne sont affichés que s’ils figurent dans la source.",en:"Current offers and discounts with direct merchant links. Codes are shown only when they appear in the source."},
"Benefit-Feed wird geladen…":{fr:"Chargement des avantages…",en:"Loading benefits feed…"},
"Sportart, Leistung, Ziele und Nachweise einreichen. PowerLux prüft Profile vor einer möglichen Veröffentlichung; Kontaktdaten bleiben privat.":{fr:"Envoyez votre sport, vos performances, vos objectifs et vos justificatifs. PowerLux vérifie les profils avant toute publication éventuelle ; les coordonnées restent privées.",en:"Submit your sport, performance, goals and evidence. PowerLux reviews profiles before any possible publication; contact details stay private."},
"01 // Kostenlos vorstellen":{fr:"01 // Présentation gratuite",en:"01 // Free submission"},
"Leistung zuerst":{fr:"La performance d’abord",en:"Performance first"},
"Sportart, Ergebnisse, Ziele und Nachweise strukturiert einreichen.":{fr:"Présentez de manière structurée votre sport, vos résultats, vos objectifs et vos justificatifs.",en:"Submit your sport, results, goals and evidence in a structured format."},
"02 // Privat":{fr:"02 // Privé",en:"02 // Private"},
"Keine öffentliche Datenbank":{fr:"Pas de base de données publique",en:"No public database"},
"Persönliche Kontaktdaten werden nicht automatisch veröffentlicht oder verkauft.":{fr:"Les coordonnées personnelles ne sont ni publiées automatiquement ni vendues.",en:"Personal contact details are not automatically published or sold."},
"Talentprofil starten":{fr:"Créer un profil talent",en:"Start talent profile"}
};

